-- Create feature usage metrics table
CREATE TABLE IF NOT EXISTS FEATURE_ENGINEERING_DB.FEATURE_ENGINEERING.FEATURE_USAGE_METRICS (
    FEATURE_NAME VARCHAR(255),
    MODEL_NAME VARCHAR(255),
    USAGE_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_USED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    USAGE_CONTEXT VARCHAR(255),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create an index on FEATURE_NAME for faster lookups
CREATE INDEX IF NOT EXISTS idx_feature_usage_metrics_feature_name 
ON FEATURE_ENGINEERING_DB.FEATURE_ENGINEERING.FEATURE_USAGE_METRICS (FEATURE_NAME);

-- Create a view for easy access to feature usage statistics
CREATE OR REPLACE VIEW FEATURE_ENGINEERING_DB.FEATURE_ENGINEERING.FEATURE_USAGE_STATS AS
SELECT 
    FEATURE_NAME,
    COUNT(*) AS usage_count,
    MAX(LAST_USED) AS last_used,
    COUNT(DISTINCT MODEL_NAME) AS models_used_in
FROM 
    FEATURE_ENGINEERING_DB.FEATURE_ENGINEERING.FEATURE_USAGE_METRICS
GROUP BY 
    FEATURE_NAME
ORDER BY 
    usage_count DESC; 