-- Create database if it doesn't exist
CREATE DATABASE IF NOT EXISTS FEATURE_ENGINEERING_DB;

-- Create schema if it doesn't exist
CREATE SCHEMA IF NOT EXISTS FEATURE_ENGINEERING_DB.FEATURE_ENGINEERING;

-- Grant usage on database and schema
GRANT USAGE ON DATABASE FEATURE_ENGINEERING_DB TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA FEATURE_ENGINEERING_DB.FEATURE_ENGINEERING TO ROLE ACCOUNTADMIN;

-- Create customer features table
CREATE OR REPLACE TABLE FEATURE_ENGINEERING_DB.FEATURE_ENGINEERING.CUSTOMER_FEATURES (
    CUSTOMER_ID VARCHAR,
    FEATURE_SET_ID VARCHAR,
    TOTAL_AMOUNT_7D FLOAT,
    AVG_AMOUNT_7D FLOAT,
    TRANSACTION_COUNT_7D INTEGER,
    UNIQUE_CATEGORIES_7D INTEGER,
    UNIQUE_PAYMENT_METHODS_7D INTEGER,
    TOTAL_AMOUNT_30D FLOAT,
    AVG_AMOUNT_30D FLOAT,
    TRANSACTION_COUNT_30D INTEGER,
    UNIQUE_CATEGORIES_30D INTEGER,
    UNIQUE_PAYMENT_METHODS_30D INTEGER,
    TOTAL_AMOUNT_90D FLOAT,
    AVG_AMOUNT_90D FLOAT,
    TRANSACTION_COUNT_90D INTEGER,
    UNIQUE_CATEGORIES_90D INTEGER,
    UNIQUE_PAYMENT_METHODS_90D INTEGER,
    LAST_UPDATE_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (CUSTOMER_ID, FEATURE_SET_ID)
);

-- Grant permissions on the table
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE FEATURE_ENGINEERING_DB.FEATURE_ENGINEERING.CUSTOMER_FEATURES TO ROLE ACCOUNTADMIN; 